package com.noop.analytics

import com.noop.analytics.WindowedStreamPlan.Plan
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Pins the windowed-read planner. Twin of Swift `WindowedStreamPlanTests` — same table, same answers,
 * generated by compiling the Swift planner standalone and pasting its output.
 *
 * Two properties matter here and nothing else does. The walk must collapse to ONE stride of reading per
 * day, which is the whole point; and every case the planner cannot prove safe must land on [Plan.FullRead],
 * because this sits on the scoring path where an optimisation that guesses produces a wrong number rather
 * than a slow one.
 */
class WindowedStreamPlanTest {

    private val day = 86_400L
    private val h30 = 108_000L
    private val midnight = 1_787_875_200L

    /**
     * The real shape: 21 days walked backwards, 54-hour windows on a 24-hour stride. Day 0 reads in full
     * because nothing is buffered; every day after it extends by EXACTLY one stride, which is the 2.25x
     * overlap being removed.
     */
    @Test fun backwardWalkExtendsByExactlyOneStridePerDay() {
        var owner: String? = null
        var cf = 0L
        var ct = 0L
        val plans = ArrayList<Plan>()
        for (offset in 0 until 5) {
            val dayStart = midnight - offset * day
            val from = dayStart - h30
            val to = dayStart + day
            plans.add(WindowedStreamPlan.plan(owner, cf, ct, false, "w", from, to))
            owner = "w"; cf = from; ct = to
        }
        assertEquals(Plan.FullRead, plans[0])
        assertEquals(Plan.Extend(1_787_680_800L, 1_787_767_199L), plans[1])
        assertEquals(Plan.Extend(1_787_594_400L, 1_787_680_799L), plans[2])
        assertEquals(Plan.Extend(1_787_508_000L, 1_787_594_399L), plans[3])
        assertEquals(Plan.Extend(1_787_421_600L, 1_787_507_999L), plans[4])
        // Each extension is one stride, inclusive at both ends — the store's range predicate is too.
        for (p in plans.drop(1)) {
            val e = p as Plan.Extend
            assertEquals(day, e.readTo - e.readFrom + 1)
        }
    }

    /** Everything the planner cannot prove safe reads in full — the pre-existing behaviour, unchanged. */
    @Test fun unprovableCasesReadInFull() {
        assertEquals(Plan.FullRead, WindowedStreamPlan.plan("a", 100, 200, false, "b", 50, 150))
        assertEquals(Plan.FullRead, WindowedStreamPlan.plan("w", 100, 200, true, "w", 50, 150))
        assertEquals(Plan.FullRead, WindowedStreamPlan.plan(null, 0, 0, false, "w", 50, 150))
        assertEquals(Plan.FullRead, WindowedStreamPlan.plan("w", 100, 200, false, "w", 10, 99))
        assertEquals(Plan.FullRead, WindowedStreamPlan.plan("w", 100, 200, false, "w", 150, 250))
        assertEquals(Plan.FullRead, WindowedStreamPlan.plan("w", 200, 100, false, "w", 50, 150))
        assertEquals(Plan.FullRead, WindowedStreamPlan.plan("w", 100, 200, false, "w", 150, 50))
    }

    /**
     * A day whose window the buffer already covers reads nothing. The boundary case is the one worth
     * pinning: `to` landing exactly ON the buffer's start still extends only up to the row below it, so the
     * boundary row is never read twice.
     */
    @Test fun coveredServesAndBoundaryNeverDoubleReads() {
        assertEquals(Plan.Serve, WindowedStreamPlan.plan("w", 100, 200, false, "w", 120, 180))
        assertEquals(Plan.Serve, WindowedStreamPlan.plan("w", 100, 200, false, "w", 100, 200))
        assertEquals(Plan.Extend(50, 99), WindowedStreamPlan.plan("w", 100, 200, false, "w", 50, 150))
        assertEquals(Plan.Extend(50, 99), WindowedStreamPlan.plan("w", 100, 200, false, "w", 50, 100))
    }

    /**
     * The saved-rows line. Twin of Swift `testLogLine` — same inputs, same string, and the shape is
     * pinned because a diagnostic nobody asserts is a diagnostic that can drift into meaning nothing.
     *
     * The zero case is the one worth having: a pass where the windows decline entirely must SAY so rather
     * than simply omit the line, so a reader can tell "the buffer saved nothing" from "the buffer was
     * never asked".
     */
    @Test fun logLineShape() {
        assertEquals(
            "analyzeRecent windows hr[read=1000 served=9000 truncated=0] " +
                "rr[read=250 served=750 truncated=3]",
            WindowedStreamPlan.logLine(1_000L, 9_000L, 0L, 250L, 750L, 3L),
        )
        assertEquals(
            "analyzeRecent windows hr[read=0 served=0 truncated=0] rr[read=0 served=0 truncated=0]",
            WindowedStreamPlan.logLine(0L, 0L, 0L, 0L, 0L, 0L),
        )
    }
}
