package com.noop.ui

import org.junit.Assert.assertEquals
import org.junit.Test

class SleepResultChangeTest {
    @Test fun resultChangeSwiftOracle() {
        val tracker = SleepResultChangeTracker()
        fun sample(scope: String = "strap:source:night", onset: Long = 1000,
                   wake: Long = 30000, asleep: Double = 420.0, edited: Boolean = false) =
            SleepResultSnapshot(scope, onset, wake, asleep, edited)
        val actual = mutableListOf<Boolean>()
        fun observe(snapshot: SleepResultSnapshot?, ready: Boolean = true) {
            actual += tracker.observe(snapshot, ready)
        }
        observe(sample())
        observe(sample())
        observe(sample("strap:source:night", 1060, 30060, 421.0))
        observe(sample("strap:source:night", 1299, 30299, 424.99))
        observe(sample("strap:source:night", 1300))
        observe(sample("strap:source:night", 1300))
        observe(sample("strap:source:night", 1300, 30300), false)
        observe(sample("strap:source:night", 1300, 30300))
        observe(sample("strap:source:night", 1300, 30300, 425.0))
        observe(sample("strap:source:night", 1300, 30300, 420.0))
        observe(sample("other-night"))
        observe(sample("other-strap"))
        observe(sample("other-strap", 2000, 31000, 430.0, true))
        observe(sample("other-strap", 3000, 32000, 440.0, true))
        observe(null)
        observe(sample())
        // Generated by the standalone Swift tracker over the identical sequence.
        assertEquals(listOf(false, false, false, false, true, false, false, true,
                            true, true, false, false, false, false, false, false), actual)
    }
}
