import XCTest
@testable import Strand

/// The unbonded Device Information Service read, ported from Android (#1647/#1649/#1653).
///
/// Since the #1635 suppression, "never bonded" is a PERMANENT state on a 5/MG rather than a transient
/// one — so a post-bond-only DIS read means such a strap never learns its firmware, its serial or whether
/// it is an MG at all. These rules decide when to try, and when to stop trying.
final class DisUnbondedReadTests: XCTestCase {

    // MARK: - when to attempt

    func testACleanFiveMGAttemptsTheRead() {
        XCTAssertTrue(shouldReadDisUnbonded(isWhoop5: true, bonded: false,
                                            alreadyReadThisLink: false, previouslyRefused: false))
    }

    /// A 4.0 bonds cleanly and its post-bond read already works, so it has no business here.
    func testAFourOhNeverAttemptsIt() {
        XCTAssertFalse(shouldReadDisUnbonded(isWhoop5: false, bonded: false,
                                             alreadyReadThisLink: false, previouslyRefused: false))
    }

    func testABondedLinkLeavesItToThePostBondPath() {
        XCTAssertFalse(shouldReadDisUnbonded(isWhoop5: true, bonded: true,
                                             alreadyReadThisLink: false, previouslyRefused: false))
    }

    func testItIsAtMostOncePerLink() {
        XCTAssertFalse(shouldReadDisUnbonded(isWhoop5: true, bonded: false,
                                             alreadyReadThisLink: true, previouslyRefused: false))
    }

    /// The self-limiting half. A read is the same class of operation as the write that provokes the
    /// teardown, so retrying one the strap has already refused risks the stable link the suppression
    /// bought — and "keeps trying something that will never work" is the failure mode this whole area
    /// keeps producing.
    func testARefusalIsPermanentForThatStrap() {
        XCTAssertFalse(shouldReadDisUnbonded(isWhoop5: true, bonded: false,
                                             alreadyReadThisLink: false, previouslyRefused: true))
    }

    // MARK: - the refusal latch key

    func testTheRefusalKeyIsCaseInsensitiveAndTrimmed() {
        XCTAssertEqual(disRefusedPrefKey("AABB-11"), "noop.disRefused.aabb-11")
        XCTAssertEqual(disRefusedPrefKey("  AABB-11 "), disRefusedPrefKey("aabb-11"))
    }

    func testTheRefusalKeyRejectsNothingToKeyOn() {
        XCTAssertNil(disRefusedPrefKey(nil))
        XCTAssertNil(disRefusedPrefKey(""))
        XCTAssertNil(disRefusedPrefKey("   "))
    }

    /// The two latches this area now persists must never collide — they answer different questions about
    /// the same strap, and one key serving both would make a DIS refusal suppress the handshake.
    func testTheDisLatchCannotCollideWithTheHelloLatch() {
        XCTAssertNotEqual(disRefusedPrefKey("aabb-11"), helloSuppressionPrefKey("aabb-11"))
    }

    // MARK: - the firmware fallback

    /// DIS is the ONLY firmware source an unbonded strap has: the puffin report needs the bond that never
    /// happens.
    func testDisFirmwarePublishesWhenNothingWasDecoded() {
        XCTAssertTrue(shouldPublishDisFirmware(disFirmware: "1.2.3", alreadyDecoded: nil))
        XCTAssertTrue(shouldPublishDisFirmware(disFirmware: "1.2.3", alreadyDecoded: ""))
        XCTAssertTrue(shouldPublishDisFirmware(disFirmware: "1.2.3", alreadyDecoded: "   "))
    }

    /// FALLBACK, never override. The puffin value is the strap's own account of what it is running and
    /// lands later in the connect; a firmware that appeared and then changed would be worse than one that
    /// arrived once.
    func testDisFirmwareNeverOverridesTheDecodedValue() {
        XCTAssertFalse(shouldPublishDisFirmware(disFirmware: "1.2.3", alreadyDecoded: "9.9.9"))
    }

    func testThereIsNothingToPublishWithoutADisString() {
        XCTAssertFalse(shouldPublishDisFirmware(disFirmware: nil, alreadyDecoded: nil))
        XCTAssertFalse(shouldPublishDisFirmware(disFirmware: "  ", alreadyDecoded: nil))
    }

    // MARK: - the failure line (byte-identical to the Kotlin twin)

    /// Generated by compiling the pure file standalone with swiftc and pasted verbatim, per the oracle
    /// rule. Without this line a refused read is indistinguishable from one never issued — the ambiguity
    /// that made the CLIENT_HELLO failure unreadable for eleven weeks.
    func testTheFailureLineIsExact() {
        XCTAssertEqual(
            disReadFailureLine(uuid: "2A26", status: "err"),
            "DIS: read of 2A26 failed err — the strap declined it on this link. If this is an insufficient-authentication or -encryption status, DIS needs an encrypted bond and the firmware cannot be read without one (#490)")
    }
}
